[project]
name = "marimo-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "marimo>=0.14.17",
    "matplotlib>=3.10.5",
    "networkx>=3.5",
    "polars>=1.32.2",
    "pyvis>=0.3.2",
    "ruff>=0.12.9",
]
